config/routes.rb
Rails.application.routes.draw do

  root "products#index"
  resources :carts do
  end
  
  resources :products, path: '/(:dept)/products'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_and_belongs_to_many :products

  include PromocodeHelper


  def checkout
    self.total_price = 0
    items = self.products.map {|product| product.price }
     total = items.inject{|sum,x| sum + x }
     if self.discount == 0 || self.discount == nil
      self.total_price = total
    else
      self.total_price = total - self.discount
    end
  end

  def is_not_empty?
    self.products != []
  end

  def set_discount
    self.discount = 0
  end

  def apply_promocode(promocode)
    self.checkout
    if self.promo_validation(promocode)
       self.discount = self.promocodes[promocode]["discount"]
       self.save
    end
  end

  def promo_validation(promocode)
    if can_apply_promocode1? || can_apply_promocode2? || can_apply_promocode3?
      promo = self.promocodes.map {|key,value| key}
      promo.include?(promocode)
    end
  end

  def remove_promocode
    self.promocode = nil
    self.discount = 0
    self.save
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_and_belongs_to_many :carts
  
  def add_to_cart
    self.quantity -= 1
    self.save
  end

  def remove_from_cart
    self.quantity += 1
    self.save
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def index
    @cart = Cart.first_or_create
    if Cart.first.is_not_empty?
      @total = Cart.first.checkout
    end
  end

  def update
    @cart = Cart.first
    @promocode = params[:cart][:promocode]
    @cart.update_attributes(cart_params)
    @cart.apply_promocode(@promocode)
    redirect_to :back
  end

  def destroy
    product = Cart.first.products.find(params[:id])
    product.remove_from_cart
    Cart.first.products.destroy(params[:id])
    Cart.first.remove_promocode
    redirect_to carts_path
  end

  private

  def cart_params
    params.require(:cart).permit(:promocode)
  end


end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @mensproducts = Product.all.select {|product| product.category.include? "Men" } 
    @womensproducts = Product.all.select {|product| product.category.include? "Women" }
    params["dept"] ||= "index"
    render params["dept"]
  end

  def mens
    @mensproducts
  end

  def womens
    @womensproducts
  end

  def update
    product = Product.find(params[:id])
    product.add_to_cart
    cart = Cart.first_or_create
    cart.products << product
    redirect_to(:back)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/promocode_helper.rb
module PromocodeHelper


  PROMOCODES = {'Promocode1' => {'description' => '£5 off', 'discount' => 5, 'qualifying purchase' => '', 'minimum spend' => 5}, 'Promocode2' =>  {'description' => '£10 off when you spend £50', 'discount' => 10, 'qualifying purchase' => '', 'minimum spend' => 50}, 'Promocode3' => {'description' => '£15 off when buy a pair of shoes and spend over £75', 'discount' => 15, 'qualifying purchase' => 'Footwear', 'minimum spend' => 50}}

  def promocodes
    PROMOCODES
  end

  def discount_applied?
    if self.discount.nil? || self.discount == 0
      return false
    else
      return true
    end
  end

  def can_apply_promocode1?
    if self.discount_applied? == false && self.total_price >= 5
      return true
    end
  end

  def can_apply_promocode2?
    if self.discount_applied? == false && self.total_price >= 50
      return true
    end
  end

  def can_apply_promocode3?
    category = self.products.map {|product| product.category}
    if self.discount_applied? == false
       self.total_price >= 75
       category.include?(self.promocodes["Promocode3"]["qualifying purchase"])
      return true
    end
  end
end

app/views/carts/index.html.erb
<div class="container">
  <div class="jumbotron cart">
    <% if %>
      <% @cart.products.length > 0 %>
      <% @cart.products.each do |product| %><br>
        <%= product.name %> <%= number_to_currency(product.price, unit: "£") %>     
        <%= link_to "Remove", cart_path(product), method: :delete, class: 'btn'%> 
      <% end %>
    <% else %>
      <%= "Your cart is empty, get shopping!" %>
    <%end%>
    <br>
    <br>
    <%= form_for @cart do |f| %>
      Promocode: <%= f.text_field :promocode %>
      <%= f.submit "Apply", :id => 'promo_apply'%>
    <%end%>
    Promocode applied: <%= @cart.promocode %>
    <br>
    Total: <%= number_to_currency(@total, unit: "£") %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>QualClothing</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js">
  </script>
</head>
<body>

<%= render 'shared/navbar' %>
<%= yield %>

</body>
</html>

app/views/products/index.html.erb
<div class="heading">
  QualClothing
</div>
<div class="col-md-12">
    <div class="row">
        <div class="col-sm-12 col-md-6 col-lg-6 men_landing_page img-responsive" style="height: 600px">
          <%= link_to image_tag("men"), products_path(:mens), id: "mens", class: "img-landing" %>
        </div>

        <div class="col-sm-12 col-md-6 col-lg-6 women_landing_page img-responsive">
          <%= link_to image_tag("http://g03.a.alicdn.com/kf/HTB1NILGIXXXXXaGXVXXq6xXFXXXF/2015-New-Arrival-Summer-Style-Women-Beach-Boho-font-b-Dress-b-font-Sexy-O-Neck.jpg"), products_path(:womens), id: "womens", class: "womensimg img-landing"%>   
        </div>
    </div>
</div>

app/views/products/male.html.erb
<div>
  <% @products.each do |product| %>
    <% if product.category.include? "Men" %>
      <div>
      <%= product.name %>: <%= product.price %> <br>
      </div>
    <% end %>
  <% end %>
</div>

app/views/products/mens.html.erb
<div class='container'>
  <div class='row'>
      <% @mensproducts.sort.each do |product| %>
      <div class=" col-lg-4 col-md-5 col-sm-6 productbox" style="padding: 0;">
        <div class="imgthumb img-responsive">
          <%= image_tag(product.id.to_s + " " + product.name) %>
        </div>
        <div class="caption">
          <%= div_for product do %>
            <h5><%= product.name %> <%= number_to_currency(product.price, unit: "£") %> 
              <br>
                Number in stock: <%= product.quantity%></h5>
                <% if %>
                  <% product.quantity <= 0 %>
                  <%= "This product is out of stock" %>
                <%else%>
                  <%= form_for product do |f| %>
                    <%= f.submit 'Add to cart', :class => 'product_add' %>
                  <%end%>
                <% end %>
        </div>
          <% end %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/products/womens.html.erb
<div class='container'>
  <div class='row'>
    <% @womensproducts.sort.each do |product| %>
      <div class=" col-lg-4 col-md-5 col-sm-6 productbox" style="padding: 0;">
        <div class="imgthumb img-responsive">
          <%= image_tag(product.id.to_s + " " + product.name) %>
        </div>
          <div class="caption">
            <%= div_for product do %>
              <h5><%= product.name %>: <%= number_to_currency(product.price, unit: "£") %><br>
                Number in stock: <%= product.quantity%>
              </h5>
                <% if %>
                  <% product.quantity <= 0 %>
                  <%= "This product is out of stock" %>
                <%else%>
                  <%= form_for product do |f| %>
                    <%= f.submit 'Add to cart', :class => 'product_add' %>
                  <%end%>
                <% end %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span> 
      </button>
      <%= link_to "QualClothing", root_path, class: "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to 'Home', products_path %></li>
        <li><%= link_to "Men's", products_path(:mens)%></li>
        <li><%= link_to "Women's", products_path(:womens)%></li> 
        <li><%= link_to "View Cart", carts_path, id: "view_cart" %> </li>
      </ul>
    </div>
  </div>
</nav>